        [connections.snowflake]
        account = "SUEXCFS-OWB51155"
        user = "TRAINMJK"
        password = "SNOW@intel1234" # Or private_key_file for key-pair authentication
        warehouse = "COMPUTE_WH"
        database = "SMOOTHIES"
        schema = "PUBLIC"
        role = "SYSADMIN"
